# [TEMPLATE] Pack & publish WebRTC Core

parameters:
  buildAgent: ''

jobs:

# Create and publish the Microsoft.MixedReality.WebRTC.Native.Core NuGet package
- job: libwebrtc_nuget
  timeoutInMinutes: 20
  pool:
    name: ${{parameters.buildAgent}}
    demands: msbuild
  variables:
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:
  - checkout: none

  # Force NuGet 4.9.2
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.9.2'
    inputs:
      versionSpec: 4.9.2
    timeoutInMinutes: 5
    
  # Generate the NuGet packages
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.nuspec
      packDestination: '$(Build.ArtifactStagingDirectory)/NuGet/'
      includeSymbols: true
      buildProperties: 'bin=bin;version=$(MRWebRTCVersion)-$(Build.BuildNumber)'
      basePath: '$(Build.SourcesDirectory)'
    timeoutInMinutes: 15

  # # Publish the NuGet packages
  # - task: PublishPipelineArtifact@0
  #   displayName: 'Publish core NuGet packages'
  #   inputs:
  #     artifactName: 'nuget_core'
  #     targetPath: '$(Build.ArtifactStagingDirectory)/NuGet'
  #   timeoutInMinutes: 15
  
  # Push packages to NuGet feed
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/NuGet/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/NuGet/**/*.symbols.nupkg'
      publishVstsFeed: '$(NuGetFeedId)'
      buildProperties: 'version=$(MRWebRTCVersion)-$(Build.BuildNumber)'

