# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

# [TEMPLATE] Compile WebRTC Core

parameters:
  buildAgent: ''
  buildArch: ''        # x86|x64|ARM|ARM64
  buildConfig: ''      # Debug|Release

jobs:

# Compile webrtc.lib (core Google implementation)
- job: libwebrtc_Win32_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool: '${{parameters.buildAgent}}'
  variables:
    buildTriple: Win32-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:
  - checkout: self
    submodules: recursive

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'Win32 ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Compile webrtc.lib
  - powershell: |
      Write-Host "Building webrtc.lib for $env:BUILD_TRIPLE..."
      # Force Python 2.7
      if (Test-Path "C:\\Python27\\python.exe")
      {
        if (Test-Path "C:\\Python27\\Scripts\\pip.exe")
        {
          $env:PATH="C:\\Python27;C:\\Python27\\Scripts;$env:PATH"
          python -m pip install --upgrade pip
          pip install pywin32
          python external/webrtc-uwp-sdk/scripts/run.py -a prepare build -t webrtc -p win --cpus $env::BUILD_ARCH -c $env:BUILD_CONFIG --noColor --noWrapper --cpp17
        }
        else
        {
          Write-Host "##vso[task.logissue type=error]Cannot find pip from C:\\Python27\\Scripts."
        }
      }
      else
      {
        Write-Host "##vso[task.logissue type=error]Cannot find python 2.7 from C:\\Python27."
      }
    env:
      BUILD_ARCH: ${{parameters.buildArch}}
      BUILD_CONFIG: ${{parameters.buildConfig}}
    timeoutInMinutes: 120
  # - task: MSBuild@1
  #   displayName: 'Build webrtc.lib ($(buildTriple))'
  #   inputs:
  #     solution: '$(projectRoot)WebRtc.Win32.Native.Builder/WebRtc.Win32.Native.Builder.vcxproj'
  #     msbuildVersion: '15.0'
  #     msbuildArchitecture: x64
  #     platform: ${{parameters.buildArch}}
  #     configuration: ${{parameters.buildConfig}}
  #   timeoutInMinutes: 120

  # Publish webrtc.lib
  - task: PublishPipelineArtifact@0
    displayName: 'Publish webrtc.lib ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/webrtc.lib'
    timeoutInMinutes: 15

  # Publish PDBs for webrtc.lib
  - task: PublishPipelineArtifact@0
    displayName: 'Publish PDBs for webrtc.lib ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_pdbs_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/pdbs'
    timeoutInMinutes: 15

