# MixedReality-WebRTC build pipeline for CI

# Disable branch and PR triggers
trigger: none
pr: none

# Give a unique name to the build each time it runs
name: mr-webrtc-libwebrtc-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:.r)

jobs:
# - template: templates/libwebrtc.yaml
#   parameters:
#     platform: 'Win32'
#     arch: 'x64'
#     buildConfig: 'Release'
- template: templates/libwebrtc.yaml
  parameters:
    platform: 'UWP'
    arch: 'x64'
    buildConfig: 'Release'
# - template: templates/libwebrtc.yaml
#   parameters:
#     platform: 'UWP'
#     arch: 'ARM'
#     buildConfig: 'Release'
